# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types:
  - pre-commit
  - prepare-commit-msg
fail_fast: true
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.5.0
      hooks:
        -   id: check-yaml
        -   id: check-symlinks
        -   id: trailing-whitespace
        -   id: end-of-file-fixer
  # - repo: local
#    hooks:
#      - id: drupal-test
#        name: Check for drupal
#        entry: ci-scripts/pre-commit-drupal.sh
#        language: script
#        pass_filenames: false
#        always_run: true
#      - id: sonar-scanner
#        name: Sonar check
#        entry: ci-scripts/sonar-scanner.sh
#        language: script
#        pass_filenames: false
#        always_run: true
